voiture_index:
    path:     /
    defaults: { _controller: "covoiturageBackOfficeBundle:Voiture:index" }
    methods:  GET

voiture_show:
    path:     /{id}/show
    defaults: { _controller: "covoiturageBackOfficeBundle:Voiture:show" }
    methods:  GET

voiture_new:
    path:     /new
    defaults: { _controller: "covoiturageBackOfficeBundle:Voiture:new" }
    methods:  [GET, POST]

voiture_edit:
    path:     /{id}/edit
    defaults: { _controller: "covoiturageBackOfficeBundle:Voiture:edit" }
    methods:  [GET, POST]

voiture_delete:
    path:     /{id}/delete
    defaults: { _controller: "covoiturageBackOfficeBundle:Voiture:delete" }
    methods:  DELETE
