api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
