covoiturage_back_office:
    resource: "@covoiturageBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /adminbo

front_office:
    resource: "@FrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
